
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class API_TearDownResourceParameters {
    /**
    * Label: Resource Name, type: textarea
    */
    String resName

    static API_TearDownResourceParameters initParameters(StepParameters sp) {
        API_TearDownResourceParameters parameters = new API_TearDownResourceParameters()

        def resName = sp.getRequiredParameter('resName').value
        parameters.resName = resName

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 81e4754e983851d71740710b69e2d516 ===
