
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class API_RunInstancesParameters {
    /**
    * Label: AMI, type: entry
    */
    String image
    /**
    * Label: Availability Zone, type: entry
    */
    String zone
    /**
    * Label: Name, type: entry
    */
    String name
    /**
    * Label: Instance Type, type: entry
    */
    String instanceType
    /**
    * Label: Subnet ID, type: entry
    */
    String subnet_id
    /**
    * Label: Security Group, type: entry
    */
    String group
    /**
    * Label: Key Name, type: entry
    */
    String keyname
    /**
    * Label: Initiated Shutdown Behaviour, type: select
    */
    String instanceInitiatedShutdownBehavior
    /**
    * Label: IAM Profile Name, type: entry
    */
    String iamProfileName
    /**
    * Label: Private IP, type: entry
    */
    String privateIp
    /**
    * Label: Tenancy, type: select
    */
    String tenancy
    /**
    * Label: User Data, type: textarea
    */
    String userData
    /**
    * Label: Number of Instances, type: integer
    */
    String count
    /**
    * Label: Resource Pool, type: entry
    */
    String res_poolName
    /**
    * Label: Use Private IP?, type: entry
    */
    String use_private_ip
    /**
    * Label: Resource Port, type: integer
    */
    String res_port
    /**
    * Label: Resource Workspace, type: entry
    */
    String res_workspace
    /**
    * Label: Resource Zone Name, type: entry
    */
    String resource_zone
    /**
    * Label: Ping Resource?, type: checkbox
    */
    boolean pingResource
    /**
    * Label: Result Property Sheet, type: entry
    */
    String propResult

    static API_RunInstancesParameters initParameters(StepParameters sp) {
        API_RunInstancesParameters parameters = new API_RunInstancesParameters()

        def image = sp.getRequiredParameter('image').value
        parameters.image = image
        def zone = sp.getParameter('zone').value
        parameters.zone = zone
        def name = sp.getParameter('name').value
        parameters.name = name
        def instanceType = sp.getRequiredParameter('instanceType').value
        parameters.instanceType = instanceType
        def subnet_id = sp.getParameter('subnet_id').value
        parameters.subnet_id = subnet_id
        def group = sp.getParameter('group').value
        parameters.group = group
        def keyname = sp.getParameter('keyname').value
        parameters.keyname = keyname
        def instanceInitiatedShutdownBehavior = sp.getParameter('instanceInitiatedShutdownBehavior').value
        parameters.instanceInitiatedShutdownBehavior = instanceInitiatedShutdownBehavior
        def iamProfileName = sp.getParameter('iamProfileName').value
        parameters.iamProfileName = iamProfileName
        def privateIp = sp.getParameter('privateIp').value
        parameters.privateIp = privateIp
        def tenancy = sp.getParameter('tenancy').value
        parameters.tenancy = tenancy
        def userData = sp.getParameter('userData').value
        parameters.userData = userData
        def count = sp.getParameter('count').value
        parameters.count = count
        def res_poolName = sp.getParameter('res_poolName').value
        parameters.res_poolName = res_poolName
        def use_private_ip = sp.getParameter('use_private_ip').value
        parameters.use_private_ip = use_private_ip
        def res_port = sp.getParameter('res_port').value
        parameters.res_port = res_port
        def res_workspace = sp.getParameter('res_workspace').value
        parameters.res_workspace = res_workspace
        def resource_zone = sp.getParameter('resource_zone').value
        parameters.resource_zone = resource_zone
        def pingResource = sp.getParameter('pingResource').value == "true"
        parameters.pingResource = pingResource
        def propResult = sp.getParameter('propResult').value
        parameters.propResult = propResult

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 7b95e689f1e68eb3024a6153cbc124ca ===
