version: '3'
services:
  efserver:
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8200:8200"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - external
    # Blocking access to maven (to force using local grapes)
    extra_hosts:
      - maven.org:127.0.0.1
      - repo1.maven.org:127.0.0.1
      - jcenter.bintray.com:127.0.0.1
    container_name: efserver
    hostname: "efserver"
    tty: true
networks:
  external:
    driver: bridge
